;;; TeXify Ada.
;;; wpl
(defun texify-ada (start end)
  "Arrange Ada in tex format."
  (interactive "r")
  (message "texifing program")
  (narrow-to-region start end)
  (shell-command-on-region (point-min) (point-max) 
			   "/users/inf/jgb/tmp/ape/ape-filter" 42 1)
  (message "fixing comments") 
  (beginning-of-buffer)
  (replace-regexp "--\\?\\([ \f\t]*\\)$" "\\\\h-")
  (beginning-of-buffer)
  (replace-regexp "--\\([ \f\t]*\\)$" "\\\\-")
  (beginning-of-buffer)
  (while (re-search-forward "^[ \t]*--\\?" nil t)
    (message "finding help comments")
    (ada-tex-help-comments))
  (beginning-of-buffer)
  (while (re-search-forward "^[ \t]*--" nil t)
    (message "finding comments")
    (ada-tex-comments))
  (beginning-of-buffer)
  (insert "\\apebegin\n")
  (end-of-buffer)
  (insert "\n\\apeend")
  (widen)
  (message "finished texifing")
  )

(defun ada-tex-comments ()
  "Arrange a series of ada comments in a tex format."
  (interactive)
  (message "fixing comment")
  (beginning-of-line)
  (push-mark nil t)
  (while (looking-at "^[ \t]*--")
    (forward-line 1))
  (beginning-of-line)
  (narrow-to-region (region-beginning) (region-end))
  (beginning-of-buffer)
  (replace-regexp "\\(^[ \t]*\\)--[ ]?\\(.*\\)" "\\1  \\2")
  (beginning-of-buffer)
  (re-search-forward "[^ \t]")
  (backward-char 3)
  (insert "\\cm{4.0in}{")
  (end-of-buffer)
  (backward-char 1)
  (insert "}\n")
  (widen)
  )

(defun ada-tex-help-comments ()
  "Arrange a series of ada help comments in a tex format."
  (interactive)
  (message "fixing help comment")
  (beginning-of-line)
  (push-mark nil t)
  (while (looking-at "^[ \t]*--")
    (forward-line 1))
  (beginning-of-line)
  (narrow-to-region (region-beginning) (region-end))
  (beginning-of-buffer)
  (replace-regexp "\\(^[ \t]*\\)--[ ]?\\?\\(.*\\)" "\\1  \\2")
  (beginning-of-buffer)
  (re-search-forward "[^ \t]")
  (backward-char 4)
  (insert "\\hcm{4.0in}{")
  (end-of-buffer)
  (backward-char 1)
  (insert "}\n")
  (widen)
  )





